#!/bin/sh

get_datetime() {
    date +" %a %d-%b %I:%M %p"
}


get_status() {
    echo "$(get_datetime)";
}

get_volume() {
    echo $(amixer get Master | grep "Right" | grep -Po "\[[0-9]{2,3}%\]")
}

get_net_state() {
    STATE=$(cat /sys/class/net/wlan0/operstate)
    if [ $STATE == "up" ]
    then
        printf " "
    else
        printf "睊"
    fi
}

while true
do
    STATUS=" $(get_net_state) ┃  $(get_volume) ┃ $(get_status)  "
    xsetroot -name "$STATUS"
    sleep 1m;
done &
