#!/bin/sh

get_datetime() {
    date +" %a %d-%b %I:%M %p"
}

get_status() {
    echo "$(get_datetime)";
}

get_volume() {
    echo $(amixer get Master | grep "Right" | grep -Po "\[[0-9]{2,3}%\]")
}

get_wifi_name() {
	echo $(nmcli d wifi list | grep -P "\*" | awk '{print $3}')
}

get_net_state() {
    STATE=$(cat /sys/class/net/wlp2s0/operstate)
    if [ $STATE == "up" ]
    then
        printf " "
    else
        printf "睊"
    fi
}

while true
do
    STATUS=" $(get_wifi_name) $(get_net_state) ┃  $(get_volume) ┃ $(get_status)  "
    xsetroot -name "$STATUS"
    sleep 1m;
done &
